### ISSUE TITLE
Track *ring* 0.17 public API changes

### ISSUE THREAD

**Issue by ctz** [aws/aws-lc-rs#245]
### Problem:

"Upstream" ring 0.17 contains some public API changes. This means the ring-compatible API offered by aws-lc-rs has diverged. Ideally aws-lc-rs would track the ring public API changes.

https://crates.io/crates/public-api could be a building block in automatically checking the two APIs do not contain unexpected differences.

**Comment by skmcgrail** [comment]
We are open to taking additional API features or enhancements from future Ring releases if they can be done in a backwards compatible manner without a major version bump, or that don't overlap features we've made available under our own APIs.

We can leave this issue open for now, so that we can track investigating what we could consider pulling in under the above guidance.

**Comment by skmcgrail** [comment]
Just dropping some high-level bullet points that I categorized from the changes I saw, and what I believe would be backwards compatible versus incompatible. No determination on what we would want to take.

# aead

## Backwards Compatible
* `aead::Aad<A>` no longer require `A` impl of `AsRef<[u8]>`.
* `LessSafeKey::open_in_place_separate_tag` function was added.
* `Tag` impl `From<[u8; 16]>` and `TryFrom<&[u8]>`.
* `Tag` has an associated type now, `Tag::Error = error::Unspecified`.

## Backwards Incompatible
* `LessSafeKey::seal_in_place`
* `SealingKey<N>::seal_in_place`

# aead::chacha20_poly1305_openssh

## Backwards Compatible
* `OpeningKey::new` returns `Self`
* `SealingKey::new` returns `Self`
* `TAG_LEN` no longer defined to match the private `BLOCK_LEN` constant. It is now set to the same length as `aead::TAG_LEN` from the parent module.

# agreement

## Backwards Compatible
* `Algorithm::eq` now takes `&Self` for other rather then explicitly using the type name.
* `UnparsedPublicKey<B>` had the `B` generic relaxed to not be required to be `AsRef<[u8]>` thus `UnparsedPublicKey<B>` may no longer implement `AsRef<[u8]>`, `Clone`, `Copy`, `Debug` only if `B` is implements `AsRef<[u8]>`.

## Backwards Incompatible
* `agree_ephemeral` no longer takes a generic parameter `F: FnOnce(&[u8]) -> R`. Instead it is defined as `impl FnOnce(&[u8]) -> R` as an anonymous type parameter. This change is considered breaking. See [Rust Reference](https://doc.rust-lang.org/reference/types/impl-trait.html#anonymous-type-parameters).
* `agree_ephemeral` no longer takes a generic error parameter `E`. The Result error type is now defined as `error::Unspecified`.

# digest

## Backwards Compatible
* `Algorithm` added `block_len()`, `chaining_len()`, and `output_len()` methods.

## Bacwards Incompatible
* `Algorithm` fields were made private: `block_len`, `chaining_len`, `output_len`

# error

## Backwards Compatible
* `Unspecified` impl `From<untrusted::reader::EndOfInput>`.

## Backwards Incompatible
* `KeyRejected::description_(...)` removed.
* `KeyRejected` no longer implements `From<untrusted::EndOfInput>`.

# hmac

## Backwards Incompatible
* `Signature`, `SigningContext`, `SigningKey`, and `VerificationKey` type aliases previously deprecated were removed.

# signature

## Backwards Compatible
* `RsaKeyPair` relocated and aliased to `rsa::KeyPair`
* `RsaPublicKeyComponents<B>` relocated and aliased to `rsa::PublicKeyComponents<B>`
* `RsaPublicKeyComponents<B>` has had `B` relaxed to not require impl `AsRef<[u8]> + Debug`
* `UnparsedPublicKey<B>` has had `B` relaxed to not require impl `AsRef<[u8]>`

## Backwards Incompatible
* `RsaSubjectPublicKey`and `RsaParameters` were removed and moved to `rsa` module as `PublicKey` and `RsaParameters` respectively.
* `EcdsaKeyPair::from_pkcs8` has a third argument now, `&dyn ring::rand::SecureRandom`.
* `EcdsaKeyPair::from_private_key_and_public_key` has a third argument now, `&dyn ring::rand::SecureRandom`.
* `EcdsaVerificationAlgorithm::verify`, `EdDSAParameters::verify` arguments now take `untrusted::input::Input` instead of `untrusted::Input`.
* `RSA_*` type constants had their types changed due to the relocation of `RsaParameters` to outside the module.

# rsa

Module is new but contains types that were originally in `signature`. I have indicated modifications to this 

## Deprecated
* `KeyPair::public_modulus_len(...)` replaced by `KeyPair::public().modulus_len()

## Backwards Compatible
* `RsaPublicKeyComponents<B>` relaxed `B` generic for the verify impl to not require Debug trait implementation, now only implements Debug trait if B implements it.
* `PublicKey::modulus_len(..) -> usize` has been added that reports the modulus length.
* New type `KeyPairComponents` that exposes the RSA private key componenets, and embeds the public key componenets type.

## Backwards Incompatible
* `PublicKey::modulus()` and `PublicKey::exponent()` removed.

**Comment by joshtriplett** [comment]
Ran into this today when trying to do `use aws_lc_rs as ring`:

> `EcdsaKeyPair::from_pkcs8` has a third argument now, `&dyn ring::rand::SecureRandom`.

I can work around this with `cfg`, but it'd be nice to match the current ring API for convenience.

**Comment by justsmth** [comment]
Since there are no specific action items for us to take on this issue now, I'll close it.

If there are any specific (backwards compatible) API changes that you would like to request us make to improve our ring compatibility, let us know. Thanks!
