### ISSUE TITLE
update untrusted dependency to 0.9.0

### ISSUE THREAD

**Issue by bdaehlie** [aws/aws-lc-rs#468]
### Problem:

aws-lc-rs uses an older version of the untrusted crate, v0.7.1. This means that when used with software that uses a newer version of untrused (e.g. Rustls) there are two versions of untrusted used.

### Solution:

Update to untrusted 0.9.0.

### Requirements / Acceptance Criteria:

No change to existing functionality, all tests should pass.

**Comment by justsmth** [comment]
Hello! 

One way to (potentially) avoid a dependency on `untrusted` v0.7.1 is to disable default features for `aws-lc-rs`, as we only expose the APIs that require this dependency when our *ring-sig-verify* feature is enabled. (Unfortunately *ring-sig-verify* is a default feature.) I agree that this is not ideal. 

The reason we've been unable to update that dependency is that the [`Input` struct](https://docs.rs/untrusted/0.7.1/untrusted/struct.Input.html) from `untrusted` v0.7.1 is part of `ring` v0.16's [VerificationAlgorithm trait](https://docs.rs/ring/0.16.20/ring/signature/trait.VerificationAlgorithm.html). Since we try to maintain compatibility with that version of ring, we [inherited that dependency here](https://docs.rs/aws-lc-rs/latest/aws_lc_rs/signature/trait.VerificationAlgorithm.html), but we marked it as deprecated.

We've considered removing or updating this dependency, but wish to avoid breaking any consumers that might be using it.  A first step might be to remove *ring-sig-verify* from our default features, but even that would technically be a violation a SemVer.

Let us know what your thoughts are on mitigating the impact of this on our consumers.

**Comment by bdaehlie** [comment]
I think Rustls already attempts to disable it, which I did not know before I filed this.

You know more about your users and their needs than I do, so I don't have more useful thoughts on the path forward than you do. I'm also not sure if you have other things you could include in new breaking release that might make it worthwhile. Probably not worth it just to remove ring-sig-verify.
