### ISSUE TITLE
SSLeay License

### ISSUE THREAD

**Issue by jayvdb** [aws/aws-lc-rs#565]
### Problem:

https://github.com/aws/aws-lc-rs/commit/8e1838777062204cd632b793d2b63d11085d0293 added the SSLeay License to `aws-lc-fips-sys/LICENSE` and `aws-lc-sys/LICENSE`

As a result this also impacts aws-lc-rs which depends those crates.

It is not an OSS license, has no SPDX identifier, etc.

### Solution:

If it isnt necessary, remove it, or at least move it to a different file with some explanation as it why it is there.

If it is a necessary license, explain somewhere why it is there, and why downstream users should not be worried that it is there.

**Comment by justsmth** [comment]
Hello --


As you may know, AWS-LC is a fork of BoringSSL, which is itself a fork of OpenSSL. (The fork for BoringSSL occurred back when OpenSSL was still under the OpenSSL license.) Work that has since been done specifically for aws-lc-rs, aws-lc-sys, aws-lc-fips-sys and AWS-LC are available under the Apache-2.0 license OR the ISC license. Licensing information for AWS-LC can be found here: https://github.com/aws/aws-lc/blob/main/LICENSE

Simplifying our licensing by the replacement, removal or relicensing of the original OpenSSL code might be possible in the future, but is not something for which we have immediate plans to announce.

We will be sure to inform the community about any future changes to our licensing.

------------
### Notes


* A related question was also asked a few months ago here: https://github.com/aws/aws-lc/issues/1441


> It is not an OSS license, has no SPDX identifier, etc.

* "OpenSSL" is listed in the [SPDX license list](https://spdx.github.io/spdx-spec/v2.2.2/SPDX-license-list/) and is also documented here: https://spdx.org/licenses/OpenSSL.html

**Comment by jayvdb** [comment]
Interesting.  I have yet had to dig into the OpenSSL/BoringSSL licensing dance, so I am coming in a bit cold on this one.  I get nervous whenever I see extra licenses and terms in the LICENSE files.

Yes, I see SSLeay is also mentioned at https://boringssl.googlesource.com/boringssl/+/refs/heads/master/LICENSE

https://openssl-library.org/source/license/index.html indicates that for earlier versions it is dual licensed

> .. [the dual OpenSSL and SSLeay license](https://openssl-library.org/source/license/license-openssl-ssleay.txt) ..

As SSLeay doesnt have a SPDX, this dual licensing cant be expressed in that system. 

However a note in the LICENSE files here, or a separate file, could explain this an bit better, but I understand if this project is not interested in doing anything except pointing out that everyone is happy with the BoringSSL license text, so "not your problem".

**Comment by justsmth** [comment]
See work being done here: https://github.com/aws/aws-lc/pull/3091

We will also be updating the licensing for our -sys crates to align.
