### ISSUE TITLE
New release for aws-lc-sys, please

### ISSUE THREAD

**Issue by asomers** [aws/aws-lc-rs#591]
### Problem:

The builds of current aws-lc-sys releases are broken on FreeBSD.  The build got broken by 8510fd10a3c3579a931d03fcb4caf008ea6034bf and that breakage made it into the 0.21.0 and 0.22.0 releases.  But it's already fixed, by 5f19caea9e4be0dd8ec1999ba449093f903769b2 .  However, that change hasn't yet made it into a new release.

The error is:
```
cargo build --features=bindgen
...
  bindgen-STDERR: error: Found argument '--prefix-link-name' which wasn't expected, or isn't valid in this context
```
This is an awkward problem, because Cargo doesn't have a good way to limit transitive dependencies.

### Solution:

Publishing a new 0.22.1 patch release would neatly solve this problem.

**Comment by merklefruit** [comment]
I am also encountering this issue and second that a patch release would be really neat.

**Comment by justsmth** [comment]
Hello! I'm sorry about this build failure.

My first thought was that you might workaround this by setting `AWS_LC_SYS_EXTERNAL_BINDGEN=0`:
```
AWS_LC_SYS_EXTERNAL_BINDGEN=0 cargo build --features=bindgen
```
However, I think the current release of `aws-lc-sys` essentially ignores the flag on FreeBSD. 😔 (Also, specifying the bindgen feature shouldn't be required, but let me know if I'm wrong.)

I'm curious about the change that broke the build. The option it's complaining about (`--prefix-link-name`) has been used [since v0.16.0](https://github.com/aws/aws-lc-rs/pull/402/files)? 🤔

Which version of bindgen are you using? Perhaps that option is not supported on older versions?

```
❯ bindgen --version
bindgen 0.70.1
```

Anyways... we plan to have a new release very soon! I'll update here when it's available.

**Comment by asomers** [comment]
Locally, I had an old version of bindgen installed: 0.55.1.  Removing that and installing bindgen-cli 0.70.1 fixed the problem.  However, nothing in my CI configuration explicitly installs either bindgen or bindgen-cli.  Maybe that's the problem?  Did aws-lc-sys 0.20.1 switch from using the bindgen library to the bindgen CLI?

**Comment by justsmth** [comment]
> Did aws-lc-sys 0.20.1 switch from using the bindgen library to the bindgen CLI?

Yeah, we initially thought that there was an issue with our [internal bindings generation when using FreeBSD](https://github.com/aws/aws-lc-rs/issues/476). We found that external bindgen was working so we forced external bindgen on FreeBSD. But after reports of similar issues on other platforms, we realized that the problem was actually with the [version of bindgen we were on and Clang 19](https://github.com/rust-lang/rust-bindgen/issues/2945). Once that got resolved, we [restored the use of internal bindgen](https://github.com/aws/aws-lc-rs/pull/561). It's been a roller coaster! 🎢 😀

**Comment by darylmartin100** [comment]
@justsmth just finished releasing 1.11.0.  Please give that a shot and let us know if you have any issues!

**Comment by asomers** [comment]
Works for me.  Thanks!
